### ISSUE TITLE
New window via menubar won't work on Windows user with spaces

### ISSUE THREAD

**Issue by Cassolette** [Cassolette/Transformice-Electron#9]
```
Error: spawn "C:\Users\User with Spaces\Transformice-Electron\
node_modules\electron\dist\electron.exe" ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
```

**Comment by Cassolette** [comment]
Known issue @ `https://github.com/nodejs/node/issues/7367`
